### ISSUE TITLE
cannot open $HOME/.nimble/lib/system.nim

### ISSUE THREAD

**Issue by evacchi** [dom96/choosenim#10]
Freshly installed copy, trying to build https://github.com/evacchi/nimoy on macOS Sierra

     Error: Traceback (most recent call last)
        ... nimble.nim(1073)         nimble
        ... nimble.nim(991)          doAction
        ... nimble.nim(973)          execHook
        ... packageparser.nim(313)   getPkgInfoFromFile
        ... packageparser.nim(288)   readPackageInfo
        ... Could not read package info file in <OMISSIS>/nimoy/nimoy.nimble;
        ...   Reading as ini file failed with:
        ...     Invalid section: .
        ...   Evaluating as NimScript file failed with:
        ...     Error: cannot open '/Users/evacchi/.nimble/lib/system.nim'.

in fact the file is missing

```
% ls /Users/evacchi/.nimble/lib/system.nim                                        
ls: /Users/evacchi/.nimble/lib/system.nim: No such file or directory
```

**Comment by dom96** [comment]
``nimble -v``?

**Comment by dom96** [comment]
Also, there is a relevant troubleshooting section for this https://github.com/nim-lang/nimble#troubleshooting

**Comment by evacchi** [comment]
nimble -v:

```
nimble v0.8.2 compiled at 2017-05-08 11:10:58
```
please notice that this happens with a fresh install of `choosenim`, which I guess is not expected.

If I install from git and put `$MY_PATH_TO/nim/bin` in my $PATH everything works as usual

**Comment by dom96** [comment]
Relevant IRC discussion: https://irclogs.nim-lang.org/08-05-2017.html#14:17:01

The problem is that the 0.16.0 Nim archive contains Nimble 0.8.2. This version of Nimble is unable to find the Nim standard library correctly.

Possible solutions:

* Introduce release channels for Nimble and don't install Nimble from the Nim release's archive.
  * Allow selection of Nimble versions independent of Nim version
* Give the user a warning that Nimble will fail because it's outdated.

**Comment by evacchi** [comment]
I think option 2 might be better; also, you may add a notice like

     You might want to try `choosenim #v${selected-version}`

if checking out from git might work
