### ISSUE TITLE
Add a command to remove versions

### ISSUE THREAD

**Issue by Calinou** [dom96/choosenim#123]
Currently, there doesn't seem to be a command like `choosenim remove <version>` to remove an installed version. Removing versions can still be done manually by removing directories in `$HOME/.choosenim/toolchains/`, but having a built-in command would be more user-friendly.

This command should probably only work on versions downloaded by choosenim, not on self-provided versions.

**Comment by sschwarzer** [comment]
Even if removing the directory happens to work, users shouldn't have to rely on this if it's not documented. After all, just deleting something might break things (with choosenim or elsewhere).

**Comment by madranet** [comment]
**+1**

Just updated to the latest 1,0,6 stable release today and was a bit gob-smacked to find `choosenim` has no built-in command to remove old or obsolete versions.

Didn't think that one through, did you?

**Comment by dom96** [comment]
> Didn't think that one through, did you?

I did actually. Maybe you should think it through a bit more? A) this software is developed voluntarily B) there are always more important things to implement than features which have an easy alternative (`rm -r ~/.choosenim/toolchains/nim-version`).

**Comment by madranet** [comment]
>I did actually...

A strange decision then

>this software is developed voluntarily...

What has that got to do with anything?

If a piece of software consecutively downloads new 'stuff' and stores it on my computer, I don't think it's being too contentious to presume it would have a built-in way of removing stale versions.  Otherwise it's a bit like building a bath tub without a plug-hole.

>features which have an easy alternative (rm -r ~/.choosenim/toolchains/nim-version)

The alternative might be "easy"  for the person who wrote the software but as @sschwarzer said above, it's not documented. So how is the user meant to know that it's safe to just `rm` that directory? [and, presumably `~/.choosenim/downloads/nim-version)` too?] Many pieces of software will break if you start deleting installed files and folders directly, without going through the correct uninstall procedure.  

Even if you don't consider it worth your time or inclination to implement such an uninstall feature within the software itself, would it have hurt to have included a line in the `choosenim -help` section that said something like _"To remove an earlier Nim version, just delete the corresponding `~/.choosenim/toolchains/nim-version)` and `~/.choosenim/downloads/nim-version)` directories"_?


For what it's worth, after updating yesterday, I tried:

```
choosenim uninstall 1.0.0
choosenim remove 1.0.0
choosenim delete 1.0.0
choosenim cleanup
choosenim autoremove
```
before resorting to RTFM with the `-help` flag, where I saw there was nothing mentioned there about uninstalling. So I headed over to Github  to see if there was any more info here about whether there was an official way to actually remove a stale version without breaking something.  

Maybe I thought it through too much!

**Comment by dom96** [comment]
>> this software is developed voluntarily...

> What has that got to do with anything?
The reason I highlighted this is because it seems you forgot it. It's fair
to want a feature, but saying "You didn't think that through, did you?" is
pretty freaking rude, don't you think? It would be rude if you wrote that
to a maintainer of software you paid for, but saying something like this in
the bug tracker of an open source tool (which hasn't even had a 1.0 release
I might add) is ridiculous.

**Comment by sschwarzer** [comment]
> The alternative might be "easy" for the person who wrote the software but as @sschwarzer said above, it's not documented.

In a way it's documented now - in this ticket. :-) Not as good as in the "official" documentation, but better than nothing.

Apart from that, I agree with @dom96 that voicing entitlement towards an open source project developed in developers' spare time isn't exactly nice.

**Comment by madranet** [comment]
> I agree with @dom96 that voicing entitlement... isn't exactly nice.

How the hell did I "voice entitlement"?

**Comment by SolitudeSF** [comment]
> No. I don't think that.
It was a tongue in cheek remark, meant as a light-hearted dig. I sometimes forget that everyone on the internet these days is such a snowflake that the slightest hint of criticism, no matter how jocularly expressed, is treated like a hate crime.

not everybody is snowflake, you just lack self awareness, which is not surprising.

**Comment by madranet** [comment]
![2019-02-06_14-32-50](https://user-images.githubusercontent.com/669658/73272973-273a5900-41db-11ea-81db-f57f310382c8.png)

**Comment by Calinou** [comment]
I guess it's time to paste my anti-bump notice :wink: 

To @madranet:

> Please don't bump issues without contributing significant new information; use the :+1: reaction button on the first post instead.

**Comment by 4A47** [comment]
Is this still not implemented and still not documented? Out of spite to madranet?

**Comment by genotrance** [comment]
Just time.

**Comment by dom96** [comment]
I can assure you that I haven't thought about this issue since my response in January. I agree that we should implement this.

**Comment by dom96** [comment]
For those doing hacktoberfest wanting to pick this up: you simply need to add a new subcommand (`remove`), have it verify that the version specified exists and then call `removeDir` to remove it.
