### ISSUE TITLE
Encrypt proxyexe to avoid stupid antivirus warnings?

### ISSUE THREAD

**Issue by dom96** [dom96/choosenim#234]
https://forum.nim-lang.org/t/6950#43511

Alternatively we could get rid of the proxy exe, but that would reduce our compatibility with various Windows OS'

**Comment by wiltzutm** [comment]
Great suggestion!

Could you guys give some boost to the priority of this issue? At the moment I cannot use Choosenim at all on my windows 10 laptop because the antivirus is whining about false suspicion: Suspicious:W32/Malware!DeepGuard. I cannot whitelist the file because I don't have admin rights.

I know this isn't really your problem, but it would help everyone with a administered PC/laptop with sucky antivirus! :)
Thank you, whatever you decide!

**Comment by wiltzutm** [comment]
This is not much related to the issue at hand, but I got a word out to my virus scanner provider (F-secure) and they made a fix for choosenim, which seemed to work on my initial test.

**Comment by dom96** [comment]
This won't help, we're getting av warnings on Nimble and other innocent Nim exes.

**Comment by wiltzutm** [comment]
Omg I'm positively surprised that you guys still worked on this! :) So yeah it's not really relevant on my case anymore because I just started using my own linux laptop when doing some hobbyish things with Nim.
Of course I understand that it's a pretty severe problem at large and I'm sorry to hear that the virus (scanner) vendors are black listing nim tools and code in general...
Thank you for all your efforts!
