### ISSUE TITLE
choosenim should be published to nimble for ease of use

### ISSUE THREAD

**Issue by timotheecour** [dom96/choosenim#56]
```
nimble install choosenim
    Prompt: choosenim not found in any local packages.json, check internet for updated packages? [y/N]
```

## workaround
```
git clone https://github.com/dom96/choosenim
cd choosenim
nimble build
# add $PWD/bin/ to PATH
```

**Comment by dom96** [comment]
hmmm. I'd rather keep things simple and not add any variables to how choosenim is installed.

We can show a nice error if someone tries it though.

**Comment by timotheecour** [comment]
* first, readme.md only mentions unix and windows, not OSX (haven't tried the UNIX approach on OSX, maybe works)
* I'm usually reluctant to install things via `curl X | sh` and I'm sure I'm not the only one
* I don't see what would be the downside of allowing `nimble install choosenim` 
* Nim should eat its own dogfood, that's how most things are installed in Nim world; makes things easier for everyone

would you accept PR's at least?

**Comment by genotrance** [comment]
This makes sense in principal but I think it makes more sense to use choosenim to install nim and nimble than to install nim and nimble first to install choosenim.

If someone were to install nim and nimble and then want to install multiple versions and need choosenim, they could use `nimble install choosenim` but then would still need to fix their paths - remove the original nim install so that the toolchains from choosenim are chosen instead from ~/.nimble/bin.

**Comment by CodeDoes** [comment]
Can't we have it both ways?

**Comment by genotrance** [comment]
I guess it's fair to `nimble publish` - it will work regardless, save for the path issue mentioned.

**Comment by genotrance** [comment]
I've created a packages PR for this.

**Comment by dom96** [comment]
This is fine, but if I start seeing a pattern of:

* User attempts to install choosenim
* Installation fails
* User is frustrated

Then I will remove this. In other words, if enabling this installation makes users confused then it will be removed.
