### ISSUE TITLE
[Feature Request] Some sort of `--force` argument for `choosenim update ...`

### ISSUE THREAD

**Issue by chrisokuda** [dom96/choosenim#88]
There is no current (known) method to force `choosenim` to fully redownload the sources and rebuild a toolchain.

**Comment by dom96** [comment]
You can ``rm`` the toolchain in ~/.choosenim/toolchains

**Comment by mcintyrechris** [comment]
Sure, but a `--force` switch would be nice, too.

**Comment by mcintyrechris** [comment]
I went ahead and implemented it in a fairly elegant way in PR #91.

**Comment by genotrance** [comment]
What's the benefit of this feature? Choosenim already allows updating [special installs](https://github.com/dom96/choosenim/blob/master/src/choosenim/channel.nim#L49) from git since those can be expected to change. It only blocks for stable versioned installs which are fixed anyway.

Only reasons would be if install failed for some reason which would be a separate bug, or if gcc compiler was changed.

**Comment by genotrance** [comment]
Third reason perhaps is to reinstall based on updates to choosenim - for example, I'm planning a PR to fix #98 which would delete c_code directory saving space. You could simply do `update --force` for an installed version and get the benefit of that fix. Of course, it isn't the best example since you can just rm -rf the directory but is an example nonetheless.

A marginally better example is PR #63 where an existing self-compiled install can be replaced with the official Nim binary ZIP for Windows.

**Comment by chrisokuda** [comment]
nevermind...
